;;; geiser-chibi-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from geiser-chibi.el

(geiser-implementation-extension 'chibi "sld")
(geiser-activate-implementation 'chibi)
(autoload 'run-chibi "geiser-chibi" "\
Start a Geiser Chibi Scheme REPL." t)
(autoload 'switch-to-chibi "geiser-chibi" "\
Start a Geiser Chibi Scheme REPL, or switch to a running one." t)
(register-definition-prefixes "geiser-chibi" '("chibi" "geiser-chibi-"))

;;; End of scraped data

(provide 'geiser-chibi-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; geiser-chibi-autoloads.el ends here
